// ignoreVideos.js
module.exports = [
  "https://www.youtube.com/watch?v=qMGjS7fVu1k",
  "https://www.youtube.com/watch?v=4tKdt9vcJXo",
  "https://www.youtube.com/watch?v=Wf-jEjVsP64",
  "https://www.youtube.com/watch?v=gW1haCLcMJs",
  "https://www.youtube.com/watch?v=-0S5pB0NA30",
  "https://www.youtube.com/watch?v=N_a0BafOLhw",
  "https://www.youtube.com/watch?v=rtu4feu5hm0",
  "https://www.youtube.com/watch?v=sTGa0HVv5Ng",
  "https://www.youtube.com/watch?v=Gyco5qmlG7w",
  "https://www.youtube.com/watch?v=qjvcRCuv6FQ",
  "https://www.youtube.com/watch?v=peoJuwmbUHo",
  "https://www.youtube.com/watch?v=veDoIqU2So0",
  "https://www.youtube.com/watch?v=0xOfPSqqgrQ",
  "https://www.youtube.com/watch?v=8oJ5GlXypQM",
  "https://www.youtube.com/watch?v=3L3xUkNZ2sA",
  "https://www.youtube.com/watch?v=_cWXGyohk8k",
  "https://www.youtube.com/watch?v=Z-3ygFVPBFM",
  "https://www.youtube.com/watch?v=9cQbRwgACzk",
  "https://www.youtube.com/watch?v=RrfOS-02kT0",
  "https://www.youtube.com/watch?v=oL5pv1LDLwk",
  "https://www.youtube.com/watch?v=3u3UBLXDWDU",
  "https://www.youtube.com/watch?v=ApvQZvHxNtA",
  "https://www.youtube.com/watch?v=mEtytXNYTaI",
  "https://www.youtube.com/watch?v=wvrnzn3zBYQ",
  "https://www.youtube.com/watch?v=HcxckpdOVpM",
  // Add more video URLs to ignore as needed
];
