name: Scheduled Podcast Workflow

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write  # Allows pushing commits

jobs:
  fetch-new-podcasts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest # Use the appropriate Node.js version here
    
    - name: Install dependencies
      run: npm install --prefer-offline --audit=false
    
    - name: Fetch podcasts
      run: |
        npm run podcasts
        npm run images
      env:
        PODCAST_API_KEY: ${{ secrets.PODCAST_API_KEY }}
        PODCAST_API_SECRET: ${{ secrets.PODCAST_API_SECRET }}
    
    - name: Commit and push changes
      run: |
        git add src/content/**/* video-aggregator/data/podcast/*
        git diff --staged --quiet || git commit -m "Github action add new podcasts"
        git push
