name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest # Use the appropriate Node.js version here

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache

      - name: Run Your Script
        uses: borales/actions-yarn@v4
        with:
          cmd: schedule
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Check for Changes
        run: |
          if [ -n "$(git diff)" ]; then
            echo "Changes detected. Staging and committing changes..."
            git add .
            git commit -m "Auto-commit: Changes detected from scheduled workflow"
            git push origin your-feature-branch
            echo "Creating a pull request..."
            gh pr create --base main --head your-feature-branch --title "Auto-generated PR" --body "Automated PR created due to changes detected from scheduled workflow."
          else
            echo "No changes detected. Skipping pull request creation."
          fi
        env:
          GH_TOKEN: ${{ github.token }}
